# Generated by Django 5.2.6 on 2025-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_rating', models.PositiveSmallIntegerField(default=0, verbose_name='Оцінка страв')),
                ('service_rating', models.PositiveSmallIntegerField(default=0, verbose_name='Оцінка сервісу')),
                ('text', models.TextField(blank=True, verbose_name='Коментар')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Контакт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
