# Generated by Django 5.2.6 on 2025-09-18 14:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-назва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва страви')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-назва')),
                ('description', models.TextField(verbose_name='Опис страви')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, help_text='Для відображення знижки', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стара ціна')),
                ('image', models.ImageField(upload_to='dishes/', verbose_name='Зображення страви')),
                ('weight', models.PositiveIntegerField(verbose_name='Вага (г)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярна страва')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Кількість лайків')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='dish.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
                'indexes': [models.Index(fields=['category', 'is_available'], name='dish_dish_categor_dcc376_idx'), models.Index(fields=['is_popular'], name='dish_dish_is_popu_01821a_idx')],
            },
        ),
    ]
