# Generated by Django 5.2.6 on 2025-09-20 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="Повне ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date', models.DateField(verbose_name='Дата бронювання')),
                ('time', models.TimeField(verbose_name='Час бронювання')),
                ('duration', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Тривалість (години)')),
                ('guests', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Кількість гостей')),
                ('zone', models.CharField(choices=[('main_hall', 'Основний зал'), ('terrace', 'Альтанка'), ('vip', 'VIP-зона')], default='main_hall', max_length=20, verbose_name='Зона')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Додаткові побажання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
