# Generated by Django 5.2.6 on 2026-04-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер столика')),
                ('seats', models.PositiveIntegerField(default=4, verbose_name='Кількість місць')),
                ('zone', models.CharField(choices=[('main_hall', 'Основний зал'), ('terrace', 'Альтанка'), ('vip', 'VIP-зона')], default='main_hall', max_length=20, verbose_name='Зона')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP столик')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['number'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='zone',
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.table', verbose_name='Столик'),
        ),
    ]
