# Generated by Django 5.2.6 on 2026-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_bonuses_earned_orderitem_bonuses_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='bonuses_earned',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='bonuses_spent',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='bonuses_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Нараховано бонусів'),
        ),
        migrations.AddField(
            model_name='order',
            name='bonuses_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Списано бонусів'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Знижка (бонусами)'),
        ),
    ]
